// <auto-generated />
using System;
using BaiThiHKH.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiThiHKH.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230629020735_HKHcau3")]
    partial class HKHcau3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("BaiThiHKH.Models.HKHcau3", b =>
                {
                    b.Property<int?>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("HKHcau3");
                });
#pragma warning restore 612, 618
        }
    }
}
